#!/usr/bin/env python3
"""
E9 shared substrate: a graph-structured AUTOREGRESSIVE per-block proposal
q_phi(W | O) = prod_j q_{phi, pi(j)}( W_{pi(j)} | W_{pi(<j)}, O ),  pi = W3 -> W2 -> W1.

Each block W_j = (raw_theta_j, c_j, U_j) is generated by its own conditional
normalizing flow, conditioned on the ALREADY-generated blocks (its separator in
the faithful inverse graph -- a chain b3-b2-b1) plus a routed observation
embedding (b3<-y, b2<-[z2,y], b1<-z1). Because the flow is autoregressive over
blocks, the exact density factorizes as log q = sum_j log q_j, so it is cheap to
evaluate -- which is what the strict IS/SMC weights and (later) GFlowNet need.

This module is deliberately objective-AGNOSTIC: the SAME SeqProposal is trained
three ways in E9 (reverse-KL VI here; VarGrad-TB GFlowNet and learned-proposal
tempered SMC to follow). Fairness rule: identical architecture, only the training
objective changes.

This file currently ships the shared proposal + the VI (reverse-KL) line and a
self-consistency / collapse smoke test on the E8 bimodal testbed.
"""

from __future__ import annotations

import argparse
import json
import math
import time
from pathlib import Path

import numpy as np
import torch

import gen_model as gm
from flow_matching import Layout
import multimodal_testbed as mm

FDTYPE = torch.float32


# --------------------------------------------------------------------------- #
# Conditional affine-coupling normalizing flow (one block)                     #
# --------------------------------------------------------------------------- #
class CondCoupling(torch.nn.Module):
    def __init__(self, dim: int, cond_dim: int, mask: torch.Tensor, hidden: int):
        super().__init__()
        self.register_buffer("mask", mask)
        self.net = torch.nn.Sequential(
            torch.nn.Linear(dim + cond_dim, hidden), torch.nn.SiLU(),
            torch.nn.Linear(hidden, hidden), torch.nn.SiLU(),
            torch.nn.Linear(hidden, 2 * dim),
        )
        torch.nn.init.zeros_(self.net[-1].weight)
        torch.nn.init.zeros_(self.net[-1].bias)

    def _st(self, x, cond):
        xm = x * self.mask
        s, t = self.net(torch.cat([xm, cond], -1)).chunk(2, -1)
        s = 1.4 * torch.tanh(s) * (1.0 - self.mask)
        t = t * (1.0 - self.mask)
        return s, t

    def forward(self, z, cond):                 # z -> x
        s, t = self._st(z, cond)
        x = z * self.mask + (1.0 - self.mask) * (z * torch.exp(s) + t)
        return x, s.sum(-1)

    def inverse(self, x, cond):                 # x -> z
        s, t = self._st(x, cond)
        z = x * self.mask + (1.0 - self.mask) * ((x - t) * torch.exp(-s))
        return z, -s.sum(-1)


class CondRealNVP(torch.nn.Module):
    def __init__(self, dim: int, cond_dim: int, n_layers: int = 8, hidden: int = 96):
        super().__init__()
        self.dim = dim
        self.layers = torch.nn.ModuleList(
            CondCoupling(dim, cond_dim, torch.tensor([(j + i) % 2 for j in range(dim)], dtype=FDTYPE), hidden)
            for i in range(n_layers)
        )
        self._c = 0.5 * dim * math.log(2 * math.pi)

    def sample_and_logq(self, cond: torch.Tensor, gen=None):
        b = cond.shape[0]
        z = torch.randn(b, self.dim, generator=gen)
        x, logdet = z, torch.zeros(b)
        for layer in self.layers:
            x, ld = layer(x, cond)
            logdet = logdet + ld
        logq = (-0.5 * (z * z).sum(-1) - self._c) - logdet
        return x, logq

    def log_prob(self, x: torch.Tensor, cond: torch.Tensor):
        z, logdet = x, torch.zeros(x.shape[0])
        for layer in reversed(self.layers):
            z, ld = layer.inverse(z, cond)
            logdet = logdet + ld
        return (-0.5 * (z * z).sum(-1) - self._c) + logdet


def mlp(sizes):
    L = []
    for a, b in zip(sizes[:-1], sizes[1:]):
        L += [torch.nn.Linear(a, b), torch.nn.SiLU()]
    return torch.nn.Sequential(*L[:-1])


# --------------------------------------------------------------------------- #
# The autoregressive graph proposal over blocks b3 -> b2 -> b1                 #
# --------------------------------------------------------------------------- #
class SeqProposal(torch.nn.Module):
    def __init__(self, layout: Layout, ny: int, nz1: int, nz2: int,
                 d_o: int = 32, d_p: int = 32, hidden: int = 96, n_layers: int = 8):
        super().__init__()
        self.L = layout
        self.ny, self.nz1, self.nz2 = ny, nz1, nz2
        self.i3 = torch.tensor(layout.b3, dtype=torch.long)
        self.i2 = torch.tensor(layout.b2, dtype=torch.long)
        self.i1 = torch.tensor(layout.b1, dtype=torch.long)
        d3, d2, d1 = len(layout.b3), len(layout.b2), len(layout.b1)
        # routed observation encoders
        self.enc_y = mlp([ny, hidden, d_o])
        self.enc_zy2 = mlp([nz2 + ny, hidden, d_o])
        self.enc_z1 = mlp([nz1, hidden, d_o])
        # previous-block encoders (separator messages)
        self.enc_p3 = mlp([d3, hidden, d_p])
        self.enc_p2 = mlp([d2, hidden, d_p])
        # per-block conditional flows
        self.f3 = CondRealNVP(d3, d_o, n_layers, hidden)
        self.f2 = CondRealNVP(d2, d_o + d_p, n_layers, hidden)
        self.f1 = CondRealNVP(d1, d_o + d_p, n_layers, hidden)

    def obs_context(self, O: torch.Tensor):
        y = O[:self.ny]; z1 = O[self.ny:self.ny + self.nz1]; z2 = O[self.ny + self.nz1:]
        return {"y": self.enc_y(y), "zy2": self.enc_zy2(torch.cat([z2, y])), "z1": self.enc_z1(z1)}

    def _assemble(self, w3, w2, w1):
        b = w3.shape[0]
        flat = torch.zeros(b, self.L.dim, dtype=FDTYPE)
        flat[:, self.i3] = w3; flat[:, self.i2] = w2; flat[:, self.i1] = w1
        return flat

    def sample(self, n: int, oc: dict, gen=None):
        e_y = oc["y"].unsqueeze(0).expand(n, -1)
        e_zy2 = oc["zy2"].unsqueeze(0).expand(n, -1)
        e_z1 = oc["z1"].unsqueeze(0).expand(n, -1)
        w3, lq3 = self.f3.sample_and_logq(e_y, gen)
        w2, lq2 = self.f2.sample_and_logq(torch.cat([e_zy2, self.enc_p3(w3)], -1), gen)
        w1, lq1 = self.f1.sample_and_logq(torch.cat([e_z1, self.enc_p2(w2)], -1), gen)
        return self._assemble(w3, w2, w1), lq1 + lq2 + lq3

    def log_prob(self, flat: torch.Tensor, oc: dict):
        n = flat.shape[0]
        w3, w2, w1 = flat[:, self.i3], flat[:, self.i2], flat[:, self.i1]
        e_y = oc["y"].unsqueeze(0).expand(n, -1)
        e_zy2 = oc["zy2"].unsqueeze(0).expand(n, -1)
        e_z1 = oc["z1"].unsqueeze(0).expand(n, -1)
        lq3 = self.f3.log_prob(w3, e_y)
        lq2 = self.f2.log_prob(w2, torch.cat([e_zy2, self.enc_p3(w3)], -1))
        lq1 = self.f1.log_prob(w1, torch.cat([e_z1, self.enc_p2(w2)], -1))
        return lq1 + lq2 + lq3


# --------------------------------------------------------------------------- #
# box-free unconstrained target (theta = tanh(raw) => support guaranteed)      #
# --------------------------------------------------------------------------- #
def target_logp(model: gm.StochasticCascade, layout: Layout, flat: torch.Tensor) -> torch.Tensor:
    W = layout.to_dict(flat)                                  # tanh applied
    lp = (model.log_trans1(W) + model.log_trans2(W) + model.log_coef_prior(W)
          + model.log_lik(W)).to(FDTYPE)
    th = torch.tanh(flat[:, layout.s_rawt])
    return lp + torch.sum(torch.log(torch.clamp(1.0 - th * th, min=1e-7)), -1)


# --------------------------------------------------------------------------- #
# Line 1 -- reverse-KL VI (pathwise; mode-seeking)                             #
# --------------------------------------------------------------------------- #
def train_vi(model, layout, prop, O, steps, batch, lr, seed):
    torch.manual_seed(seed)
    opt = torch.optim.AdamW(prop.parameters(), lr=lr, weight_decay=1e-5)
    hist = []
    for step in range(1, steps + 1):
        oc = prop.obs_context(O)                             # fresh graph each step
        flat, logq = prop.sample(batch, oc)
        logp = target_logp(model, layout, flat)
        loss = torch.mean(logq - logp)                       # KL(q||p) up to const
        opt.zero_grad(set_to_none=True)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(prop.parameters(), 25.0)
        opt.step()
        if step == 1 or step % max(1, steps // 10) == 0:
            hist.append({"step": step, "loss": float(loss.detach())})
    return hist


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=7)
    ap.add_argument("--n-sim", type=int, default=70)
    ap.add_argument("--n-field", type=int, default=30)
    ap.add_argument("--steps", type=int, default=2500)
    ap.add_argument("--batch", type=int, default=256)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--restarts", type=int, default=3)
    ap.add_argument("--outdir", type=str, default="results/e9_vi")
    args = ap.parse_args()

    torch.set_num_threads(6)
    rng = np.random.default_rng(args.seed)
    theta_true = np.array([0.35, -0.55, 0.45])
    sigma_y, sigma_z = 0.06, 0.05

    # E8 bimodal (even-theta2) testbed
    data = mm.make_field_data_even(rng, args.n_field, theta_true, sigma_y, sigma_z)
    model = mm.build_cascade_even(rng, args.n_sim, data["x"], sigma_y, sigma_z)
    model._n_sim = args.n_sim
    gm.attach_data(model, data)
    layout = Layout(model)
    O = torch.tensor(np.concatenate([data["y_obs"], data["z1_obs"], data["z2_obs"]]), dtype=FDTYPE)

    # architecture self-consistency: sample logq must equal recomputed log_prob
    probe = SeqProposal(layout, model.n, len(model.z1_idx), len(model.z2_idx))
    oc = probe.obs_context(O)
    with torch.no_grad():
        flat, lq = probe.sample(64, oc)
        lq2 = probe.log_prob(flat, oc)
    max_err = float((lq - lq2).abs().max())
    print(f"[self-consistency] max |logq_sample - logq_eval| = {max_err:.2e}  (should be ~0)")

    runs = []
    for r in range(args.restarts):
        prop = SeqProposal(layout, model.n, len(model.z1_idx), len(model.z2_idx))
        t0 = time.time()
        hist = train_vi(model, layout, prop, O, args.steps, args.batch, args.lr, args.seed + 10 + r)
        with torch.no_grad():
            flat, _ = prop.sample(4000, prop.obs_context(O))
            th2 = torch.tanh(flat[:, 1]).numpy()
        runs.append({"restart": r, "train_s": time.time() - t0,
                     "final_loss": hist[-1]["loss"], **mm.mode_report(th2)})

    n_collapsed = sum(1 for v in runs if v["minority_mass"] < 0.05)
    out = {"setup": {"seed": args.seed, "latent_dim": layout.dim, "testbed": "bimodal_even_theta2",
                     "self_consistency_maxerr": max_err},
           "vi_line": runs, "collapsed_fraction": n_collapsed / max(1, args.restarts)}
    outdir = Path(args.outdir); outdir.mkdir(parents=True, exist_ok=True)
    with (outdir / "metrics.json").open("w") as f:
        json.dump(out, f, indent=2)

    print(f"\n===== E9 Line 1: reverse-KL VI on shared autoregressive graph proposal =====")
    print(f"testbed = bimodal even-theta2  (modes at +/-0.55)   dim={layout.dim}")
    for v in runs:
        print(f"  restart {v['restart']}: theta2 neg={v['mass_neg']:.2f} pos={v['mass_pos']:.2f}  "
              f"minority={v['minority_mass']:.2f}  loss={v['final_loss']:.1f}  ({v['train_s']:.0f}s)")
    print(f"  -> VI collapsed (minority<0.05) in {n_collapsed}/{args.restarts} restarts "
          f"(expected: VI is mode-seeking).")


if __name__ == "__main__":
    main()
